stages:
  - build
  - deploy
  - dregistry

node:
  stage: build
  image: node:alpine
  before_script:
    - npm install
  script:
    - npm run build --configuration=production
  artifacts:
    paths:
      - dist/perform-front/

surge:
  stage: deploy
  image: drkms/surge.sh
  script:
    - surge --project=$PWD/dist/perform-front/ --domain="perfmma.surge.sh"
  rules:
    - when: manual

dregistry:
  stage: dregistry
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE .
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
    - docker logout
