stages:
  - build
  - deploy

node:
  stage: build
  image: node:18-alpine
  before_script:
    - npm install
  script:
    - npm run build --configuration=production
  artifacts:
    paths:
      - dist/perform-front/

surge:
  stage: deploy
  image: drkms/surge.sh
  script:
    - surge --project=$PWD/dist/perform-front/ --domain="perfmma.surge.sh"
  rules:
    - when: manual